services:
  flask_app:
    container_name: flask_app
    build: .
    ports: 
      - "4000:4000"
    environment:
      - DB_URL=postgresql://postgres:postgres@flask_db:5432/postgres
    depends_on:
      - flask_db

  flask_db:
    container_name: flask_db
    image: postgres:13
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  convergence_updater:
    container_name: convergence_updater
    build: .
    command: python populate_convergence_data.py
    depends_on:
      - flask_db
      - flask_app

  test_runner:
    container_name: test_runner
    build: .
    ports: 
      - "5000:5000"
    environment:
      - DB_URL=postgresql://postgres:postgres@flask_db:5432/postgres
    command: pytest
    depends_on:
      - flask_app
      - flask_db

volumes:
  postgres_data: {}
